# This rule is not used by the project silence-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the monitoring.giantswarm.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: silence-operator
    app.kubernetes.io/managed-by: kustomize
  name: silence-editor-role
rules:
- apiGroups:
  - monitoring.giantswarm.io
  - observability.giantswarm.io
  resources:
  - silences
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
