apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: my-sample-silence
  namespace: default
spec:
  matchers:
  - name: alertname
    value: MyPagingAlert
    matchType: "="
  - name: alertname
    value: Heartbeat
    matchType: "!="
