apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: my-sample-silence
spec:
  matchers:
  - isRegex: false
    name: alertname
    value: MyPagingAlert
  - isEqual: false
    isRegex: false
    name: alertname
    value: Heartbeat
