apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: my-sample-silence
  namespace: default
spec:
  # Time management options (choose one approach):

  # Option 1: Specify exact start and end times
  # startsAt: "2025-07-15T14:30:00Z"
  # endsAt: "2025-07-15T18:30:00Z"

  # Option 2: Use duration from start time (or creation time if startsAt not specified)
  duration: "4h"

  # Option 3: For backward compatibility, use annotation (lowest priority)
  # annotations:
  #   valid-until: "2025-07-15T18:30:00Z"

  matchers:
  - name: alertname
    value: MyPagingAlert
    matchType: "="
  - name: alertname
    value: Heartbeat
    matchType: "!="
  - name: severity
    value: critical
    matchType: "="
  - name: instance
    value: ".*prod.*"
    matchType: "=~"  # Regex match
---
# Example with explicit start and end times
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: scheduled-maintenance-silence
  namespace: default
spec:
  startsAt: "2025-07-16T02:00:00Z"
  endsAt: "2025-07-16T06:00:00Z"
  matchers:
  - name: alertname
    value: ".*Disk.*"
    matchType: "=~"
  - name: job
    value: node-exporter
    matchType: "="
---
# Example with duration-based silence
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: incident-response-silence
  namespace: default
spec:
  duration: "2h30m"
  matchers:
  - name: severity
    value: "warning|info"
    matchType: "=~"
  - name: team
    value: platform
    matchType: "="
