{{- if .Values.kyvernoPolicyExceptions.enabled }}
{{- if .Capabilities.APIVersions.Has "kyverno.io/v2alpha1/PolicyException" -}}
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ .Values.kyvernoPolicyExceptions.namespace | default (include "resource.default.namespace" .) }}
spec:
  exceptions:
  - policyName: disallow-capabilities-strict
    ruleNames:
    - require-drop-all
    - autogen-require-drop-all
  - policyName: disallow-privilege-escalation
    ruleNames:
    - privilege-escalation
    - autogen-privilege-escalation
  - policyName: require-run-as-nonroot
    ruleNames:
    - run-as-non-root
    - autogen-run-as-non-root
  match:
    any:
    - resources:
        kinds:
        - Deployment
        - Pod
        namespaces:
        - {{ include "resource.default.namespace" . }}
        names:
        - {{ include "resource.default.name" . }}*
  {{- end -}}
{{- end -}}
