{{- if .Values.namespaceEnforcement.rules }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ template "silence-operator.name" . }}-namespace-enforcement
  namespace: {{ template "silence-operator.namespace" . }}
data:
  namespace-enforcement.yaml: |
{{ toYaml .Values.namespaceEnforcement | indent 4 }}
{{- end }}
